[package]
name = "json-sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.69"
anyhow = "1.0.45"
serde = "1.0.130"
